### PR TITLE
Switch from Sub::Name to Sub::Util

### PR DESCRIPTION
**Pull request by ap**
The module depends on the Scalar-List-Utils dist already, which nowadays includes Sub::Util, so switching to it gets rid of a dependency. On recent perls it’s even in core, further diminishing the dep footprint.

Additionally, Moose itself and several MooseX::* modules have made this switch some time ago, which means this change will also cut the dep footprint of Moose, a primary downstream of this module.

### CODE REVIEW

**Comment by autarch** [comment]
Hi, thanks for your PR! I'm pretty finicky about my projects (see [this blog post](https://blog.urth.org/2022/07/02/what-s-the-right-way-to-merge-a-pull-request/) for details), so I rarely merge a PR as-is. I can move forward on your PR in one of two ways:

1. I check it out locally, fiddle with it as needed, merge it locally, and simply close this PR. This will preserve at least one commit with your name on it, but the PR will show up as closed in your GitHub stats.
2. If you enable me to push directly to your fork, I can do my fiddling, then force push to your fork and merge the resulting PR. Again, this will preserve at least one commit with your name on it, but you _also_ get credit for the PR merge in your GitHub stats. The only downside is that I will be force pushing directly to your fork.

Please let me know which approach you'd prefer. If I don't hear from you before I get around to working on this PR I'll go with option #1.

Thanks again for your contribution!

(Though I will note that last time someone picked the second option I was not able to push to their fork, even though they checked the box that would let me.)

**Comment by ap** [comment]
Whatever is easier for you is fine with me! I just want this out, I don’t care about credit whatsoever.

(But I also don’t mind being named either, if you feel more comfortable with that. Again, I am fine with doing this however makes your life easiest.)

**Comment by karenetheridge** [comment]
FWIW we made similar changes to Moose recently so you might want to look at exactly what changed there. I wholeheartedly support the removal of Sub::Name whenever it is practical to do so and functionality isn't impaired.

**Comment by autarch** [comment]
Yay, I finally made the "push to someone's PR branch" thing work. Merged!

**Comment by autarch** [comment]
This was release as v0.18.

**Pull request merged**
